# Generated by Django 4.0.4 on 2022-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('islogged', models.BooleanField(default=False)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('supervisorcode', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
                ('discount', models.BigIntegerField()),
                ('employeeId', models.BigIntegerField()),
                ('paid', models.BigIntegerField()),
                ('payable', models.BigIntegerField()),
                ('reference', models.BigIntegerField()),
                ('returned', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('vat', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('categoryId', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('supplierId', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseCurrency', models.CharField(max_length=10)),
                ('foreignCurrency', models.CharField(max_length=10)),
                ('rate', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_currency', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('cost_price', models.BigIntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('employeeId', models.BigIntegerField(null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('employee', models.CharField(blank=True, max_length=100)),
                ('foreign_currency', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=100)),
                ('invoiceId', models.BigIntegerField(null=True)),
                ('pan', models.CharField(blank=True, max_length=100)),
                ('productId', models.BigIntegerField(null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('rate', models.BigIntegerField(null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('rrn', models.CharField(blank=True, max_length=100)),
                ('shop_name', models.CharField(blank=True, max_length=100)),
                ('tax', models.BigIntegerField(null=True)),
                ('total', models.BigIntegerField(null=True)),
            ],
        ),
    ]
