# Generated by Django 4.0.4 on 2022-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.CharField(default='maheu', max_length=100),
            preserve_default=False,
        ),
    ]
