# Generated by Django 4.0.4 on 2022-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_sales_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliers_type', models.CharField(max_length=100)),
                ('suppliers_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliers_type', models.CharField(max_length=100)),
                ('suppliers_description', models.CharField(max_length=100)),
            ],
        ),
    ]
