# Generated by Django 4.0.4 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_categories_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='suppliers_description',
            new_name='categories_description',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='suppliers_type',
            new_name='categories_type',
        ),
    ]
