# Generated by Django 4.0.4 on 2022-09-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_suppliers_description_categories_categories_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='suppliers_description',
            new_name='suppliers_address',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='suppliers_type',
            new_name='suppliers_name',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='suppliers_phone',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
