# Generated by Django 4.0.4 on 2022-09-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_suppliers_description_suppliers_suppliers_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.categories'),
            preserve_default=False,
        ),
    ]
