# Generated by Django 4.0.4 on 2022-09-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_products_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='categories_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.categories'),
        ),
    ]
