# Generated by Django 4.0.4 on 2022-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_products_categories_products_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categories_id',
            field=models.IntegerField(default=1),
        ),
    ]
