# Generated by Django 4.0.4 on 2022-09-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_categories_categories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='apis.categories'),
        ),
    ]
