# Generated by Django 4.0.4 on 2022-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_products_categories_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categories_id1',
            new_name='categories_id',
        ),
    ]
