# Generated by Django 4.0.4 on 2022-09-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_rename_categories_id1_products_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='suppliers_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='suppliers_id',
            field=models.IntegerField(default=1),
        ),
    ]
