# Generated by Django 4.0.4 on 2022-09-18 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_products_suppliers_id_suppliers_suppliers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='islogged',
        ),
        migrations.CreateModel(
            name='ordersandproducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('categoryId', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('supplierId', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
                ('categories_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('suppliers_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createed_at', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(max_length=100)),
                ('categoryId', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('supplierId', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
                ('categories_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('suppliers_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
    ]
