# Generated by Django 4.0.4 on 2022-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_remove_employees_islogged_ordersandproducts_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(default='ACTIVE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(default='OFFLINE', max_length=100),
        ),
    ]
