# Generated by Django 4.0.4 on 2022-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_employees_employee_status_alter_employees_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='type',
        ),
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
