# Generated by Django 4.0.4 on 2022-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_remove_employees_type_employees_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(default='TELLER', max_length=100),
        ),
    ]
