# Generated by Django 4.0.4 on 2022-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_alter_employees_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='supervisorcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='imei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='rrn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
