# Generated by Django 4.0.4 on 2022-09-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_employees_supervisorcode_alter_sales_imei_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='products',
            name='supplierId',
        ),
        migrations.AlterField(
            model_name='employees',
            name='supervisorcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='suppliers_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
