# Generated by Django 4.0.4 on 2022-09-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_remove_products_categoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='discount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='paid',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='payable',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='total',
        ),
    ]
