# Generated by Django 4.0.4 on 2022-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_rename_discount_invoices_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='vat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
