# Generated by Django 4.0.4 on 2022-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_alter_invoices_amount_alter_invoices_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
