# Generated by Django 4.0.4 on 2022-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_alter_invoices_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
