# Generated by Django 4.0.4 on 2022-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_invoices_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
